// Generates assets/src/frontend/core/glyphs.js from Lucide (ISC) icons.
// Run: npm install --no-save lucide-static && node tools/icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const names = {
	store: 'store', shop: 'shopping-bag', cart: 'shopping-cart', restaurant: 'utensils', coffee: 'coffee', bar: 'beer',
	hotel: 'bed-double', home: 'house', office: 'building-2', bank: 'landmark', hospital: 'hospital', pharmacy: 'pill',
	doctor: 'stethoscope', school: 'graduation-cap', library: 'book-open', church: 'church', park: 'trees', mountain: 'mountain',
	camping: 'tent', beach: 'umbrella', water: 'waves', airport: 'plane', train: 'train-front', bus: 'bus', car: 'car',
	bike: 'bike', fuel: 'fuel', parking: 'square-parking', port: 'anchor', camera: 'camera', event: 'ticket', music: 'music',
	heart: 'heart', star: 'star', flag: 'flag', info: 'info', pin: 'map-pin', work: 'briefcase', service: 'wrench',
	gym: 'dumbbell', pets: 'paw-print', family: 'baby', charging: 'plug-zap', wifi: 'wifi',
};
let out = '/**\n * Marker glyphs from Lucide (https://lucide.dev), ISC License,\n * Copyright (c) Lucide Contributors. Generated by tools/icons.mjs; do not edit.\n */\n\nexport default {\n';
for (const [key, file] of Object.entries(names)) {
	const svg = readFileSync(`node_modules/lucide-static/icons/${file}.svg`, 'utf8');
	const inner = svg.replace(/[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*/, '').replace(/\s*\n\s*/g, '').replace(/ \/>/g, '/>').trim();
	out += `\t${key}: '${inner.replace(/'/g, "\\'")}',\n`;
}
out += '};\n';
writeFileSync('assets/src/frontend/core/glyphs.js', out);
console.log(Object.keys(names).length, 'glyphs');
